# Generated by Django 3.2.6 on 2021-08-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
    ]
